### ISSUE TITLE
Add mongo createdAt and updatedAt timestamps to all docs

### ISSUE THREAD

**Issue by AlexLMeow** [helloworld1812/SaferCityBackend#16]
Separate from domain object `timestamp` or `time` fields.

**Comment by by-code** [comment]
Alex, could you please elaborate who and how will use this information?

If that should be added to all docs (i.e. to "reports" and "comments" and later to "users") then it looks more like a separate "metadata"-ish entity rather than additional property of each object and then this feature should be planned and implemented separately.

**Comment by AlexLMeow** [comment]
Users only see comment timestamps. Yes this issue is for standard database record metadata. there is no use case for this data right now from the app user perspective. This timestamp tracking can be turned on in mongodb iirc

**Comment by by-code** [comment]
If there is no use let's don't add this feature right now
